apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reference-db-creator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reference-db-creator-role
subjects:
- kind: ServiceAccount
  name: reference-db-creator
  namespace: {{ .Release.Namespace }}