apiVersion: batch/v1
kind: CronJob
metadata:
  name: reference-db-creator
  labels:
    app.kubernetes.io/name: reference-db-creator
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      template:
        metadata:
          labels:
            app.kubernetes.io/name: reference-db-creator
        spec:
          serviceAccountName: reference-db-creator
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: reference-db-creator
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - python
                - manage.py
                - clean_dump_generator
              env:
                {{- range $k, $v := .Values.env }}
                - name: {{ $k | quote }}
                  value: {{ $v | quote }}
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
