apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    yandexlockbox:
      auth:
      {{- with .Values.clusterSecretStore.authSecret }}
        authorizedKeySecretRef:
          {{- toYaml . | nindent 10 }}
      {{- end }}