{{- range $externalSecret := .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
spec:
  refreshInterval: {{ $externalSecret.refreshInterval }}
  {{- with $externalSecret.secretStoreRef }}
  secretStoreRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $externalSecret.target }}
  target:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $externalSecret.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
