apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-prod
  namespace: argocd
spec:
  destination:
    namespace: todobackend
    name: {{ .Values.spec.destination.name }}
  project: default
  source:
    path: charts/external-secrets
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - ../../values/eso-prod.yaml
  syncPolicy:
    automated: {}
