apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
spec:
  destination:
    # А вот тут уже неймспейс, куда будет устанавливаться сам чарт
    namespace: external-secrets
    name: {{ .Values.spec.destination.name }}
  project: default
  source:
    # Указываем настройки до чарта
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.6.0
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
