apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  destination:
    namespace: fluentbit
    name: {{ .Values.spec.destination.name }}
  project: default
  source:
    path: charts/fluent-bit-cloud-logging
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/key.txt?../../values/fluentbit-prod.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
