apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-prod
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    name: {{ .Values.spec.destination.name }}
  project: default
  source:
    path: charts/kube-prometheus-stack
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - ../../values/monitoring-prod.yaml
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: monitoring-prod-kube-prome-admission
      jqPathExpressions:
        - .webhooks[].failurePolicy
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: monitoring-prod-kube-prome-admission
      jqPathExpressions:
        - .webhooks[].failurePolicy
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
