apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: PostgresqlDatabase
metadata:
  name: {{ .Values.dbName | replace "_" "-" }}
spec:
  forProvider:
    clusterIdRef:
      name: {{ .Values.clusterName }}
    name: {{ .Values.dbName }}
    owner: {{ .Values.username }}
